
###### List the connectors ##########

curl http://hadoop-fra-5.intern.beon.net:8083/connectors

####### Describe Connector ######

curl http://hadoop-fra-5.intern.beon.net:8083/connectors/file-source

####### Describe Connector config ######

curl http://hadoop-fra-5.intern.beon.net:8083/connectors/file-source/config

####### check the status of a Connector ######

curl http://hadoop-fra-5.intern.beon.net:8083/connectors/file-source/status


#### Restart connector #########

POST http://hadoop-fra-5.intern.beon.net:8083/connectors/file-source/restart
# curl -X POST -H http://hadoop-fra-5.intern.beon.net:8083/connectors/file-source/restart

#### Pause connector #########

PUT http://hadoop-fra-5.intern.beon.net:8083/connectors/file-sink/pause
#curl -X PUT -H http://hadoop-fra-5.intern.beon.net:8083/connectors/file-source/pause

#### Resume connector #########
PUT http://hadoop-fra-5.intern.beon.net:8083/connectors/file-sink/resume
#curl -X PUT -H http://hadoop-fra-5.intern.beon.net:8083/connectors/file-source/resume

###### Delete a Connector ###########

curl -X DELETE http://hadoop-fra-5.intern.beon.net:8083/connectors/file-source

######### Get tasks of a connector ######

curl http://hadoop-fra-5.intern.beon.net:8083/connectors/file-source/tasks

######### Restart a task of a connector ##########

POST http://hadoop-fra-5.intern.beon.net:8083/connectors/file-source/tasks/0/restart


####### Create a connector ##########

curl -d @"C:\\Rajashekar\\Git\\ScriptsForAutomation\\connect-file-source.json" \
    -H "Content-Type: application/json" \
	-X POST http://hadoop-fra-5.intern.beon.net:8083/connectors

########## Create a Source connector ###########
POST http://hadoop-fra-5.intern.beon.net:8083/connectors
Content-Type: application/json
Accept: application/json

{
    "name": "file-source",
    "config": {
        "connector.class": "FileStreamSource",
        "tasks.max": "1",
        "topic": "ITERGO_A_T5",
        "file": "/tmp/test.txt",
        "key.converter": "org.apache.kafka.connect.json.JsonConverter",
        "value.converter": "org.apache.kafka.connect.json.JsonConverter"}
}

############ Create a sink connector #########

POST http://hadoop-fra-5.intern.beon.net:8083/connectors
Content-Type: application/json
Accept: application/json

{
    "name": "file-sink",
    "config": {
        "connector.class": "FileStreamSink",
        "tasks.max": "1",
        "file": "/tmp/test.sink.txt",
        "topics": "ITERGO_A_T5",
        "key.converter": "org.apache.kafka.connect.json.JsonConverter",
        "value.converter": "org.apache.kafka.connect.json.JsonConverter"}
}

####### update the configuration for an existing connector ########

PUT http://hadoop-fra-5.intern.beon.net:8083/connectors/file-source/config
Content-Type: application/json
Accept: application/json

{
    "connector.class": "FileStreamSource",
    "tasks.max": "2",
    "topic": "ITERGO_A_KC",
    "file": "/tmp/test.txt",
    "key.converter": "org.apache.kafka.connect.json.JsonConverter",
    "value.converter": "org.apache.kafka.connect.json.JsonConverter"
}

######### Get connector plugins ########

GET http://hadoop-fra-5.intern.beon.net:8083/connector-plugins

######## Validate the provided configuration against configuration definition ########

PUT http://hadoop-fra-5.intern.beon.net:8083/connector-plugins/FileStreamSourceConnector/config/validate
Content-Type: application/json
Accept: application/json

{
    "connector.class": "FileStreamSource",
    "tasks.max": "2",
    "topic": "ITERGO_A_KC",
    "file": "/tmp/test.txt",
    "key.converter": "org.apache.kafka.connect.json.JsonConverter",
    "value.converter": "org.apache.kafka.connect.json.JsonConverter"
}
