
GET http://hadoop-fra-5.intern.beon.net:8081/subjects

###############
GET http://hadoop-fra-5.intern.beon.net:8081/subjects
Authorization: Basic harry changeme

###################

GET http://hadoop-fra-5.intern.beon.net:8081/subjects/transactions-value/versions

####################

GET http://hadoop-fra-5.intern.beon.net:8081/subjects/transactions-value/versions/1

########

POST http://hadoop-fra-5.intern.beon.net:8081/subjects/transactions1-value/versions
Content-Type: application/vnd.schemaregistry.v1+json

{
    "schema": "{ \"type\":\"record\", \"name\":\"Payment\", \"namespace\":\"io.confluent.examples.clients.basicavro\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"amount\",\"type\":\"double\"}]}" 
}

#############

curl http://hadoop-fra-5.intern.beon.net:8081/subjects

##########

curl http://hadoop-fra-5.intern.beon.net:8081/subjects/transactions-value/versions